### ISSUE TITLE
NoMethod bug in ALPHA postgres port

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan_api#122]
api_1       | 172.19.0.1 - - [16/Jan/2018:15:47:19 +0000] "GET /api/v1/scan/results?uuid=ee8a66e7-4d4b-410b-9eda-aa49d6ce22d1 HTTP/1.1" 200 18 0.0015
api_1       | 2018-01-16 15:47:19 - NoMethodError - undefined method `+' for nil:NilClass:
api_1       | 	/app/lib/ssh_scan_api/database/postgres.rb:147:in `block in grade_report'
api_1       | 	/app/lib/ssh_scan_api/database/postgres.rb:146:in `each'
api_1       | 	/app/lib/ssh_scan_api/database/postgres.rb:146:in `grade_report'
api_1       | 	/app/lib/ssh_scan_api/database.rb:65:in `grade_report'
api_1       | 	/app/lib/ssh_scan_api/api.rb:212:in `block (2 levels) in <class:API>'

Note that this only affects https://github.com/mozilla/ssh_scan_api/pull/121

**Comment by claudijd** [comment]
Repro Steps

1.) Stand up a docker-based infra
2.) run a scan end-to-end
3.) then visit the /api/v1/stats route and get an "internal error", which is the result of this exception

**Comment by claudijd** [comment]
Fixed in https://github.com/mozilla/ssh_scan_api/pull/121/commits/34e0fbe06083248c7764c72c909e42d272ea228a
