### ISSUE TITLE
PStore::Error in Postgres Alpha

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan_api#123]
worker_1    | I, [2018-01-16T18:39:27.116258 #1]  INFO -- : Started job: ad68824e-b029-4709-b442-7d01217a5f94
worker_1    | /usr/local/lib/ruby/2.5.0/pstore.rb:122:in `initialize': directory /app/lib/ssh_scan_api/../../data does not exist (PStore::Error)
worker_1    | 	from /usr/local/lib/ruby/2.5.0/yaml/store.rb:58:in `initialize'
worker_1    | 	from /usr/local/bundle/gems/ssh_scan-0.0.28/lib/ssh_scan/fingerprint_database.rb:7:in `new'
worker_1    | 	from /usr/local/bundle/gems/ssh_scan-0.0.28/lib/ssh_scan/fingerprint_database.rb:7:in `initialize'
worker_1    | 	from /usr/local/bundle/gems/ssh_scan-0.0.28/lib/ssh_scan/scan_engine.rb:201:in `new'
worker_1    | 	from /usr/local/bundle/gems/ssh_scan-0.0.28/lib/ssh_scan/scan_engine.rb:201:in `scan'
worker_1    | 	from /app/lib/ssh_scan_api/worker.rb:101:in `perform_work'
worker_1    | 	from /app/lib/ssh_scan_api/worker.rb:44:in `block in run!'
worker_1    | 	from /app/lib/ssh_scan_api/worker.rb:38:in `loop'
worker_1    | 	from /app/lib/ssh_scan_api/worker.rb:38:in `run!'
worker_1    | 	from /app/bin/ssh_scan_worker:16:in `<main>'
worker_1    | wait-for-it.sh: waiting 15 seconds for api:8000
worker_1    | wait-for-it.sh: api:8000 is available after 0 seconds

This only affects https://github.com/mozilla/ssh_scan_api/pull/121

**Comment by claudijd** [comment]
Fixed in https://github.com/mozilla/ssh_scan_api/pull/121/commits/27c1739e6bf8ec9e0b9ccd7cce2a703b7047b142 (this was a result of moving to the Docker Base strategy where the workers didn't have access to policies anymore)
