### ISSUE TITLE
500 error from API endpoint

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan_api#52]
Reproduction with...

curl -X POST https://sshscan.rubidus.com/api/v1/scan?target=mozilla.org

**Comment by claudijd** [comment]
$ curl -X POST https://sshscan.rubidus.com/api/v1/scan?target=mozilla.org
ArgumentError: no time information in ""
	/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/time.rb:254:in `make_time'
	/usr/local/rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/time.rb:366:in `parse'
	/root/code/ssh_scan_api/lib/ssh_scan_api/api.rb:60:in `cache_valid?'
	/root/code/ssh_scan_api/lib/ssh_scan_api/api.rb:140:in `block (2 levels) in <class:API>'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1632:in `block in compile!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (3 levels) in route!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1010:in `route_eval'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:991:in `block (2 levels) in route!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1037:in `block in process_route'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `catch'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1035:in `process_route'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:989:in `block in route!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `each'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:988:in `route!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1094:in `block in dispatch!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/secure_headers-3.6.4/lib/secure_headers/middleware.rb:12:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-protection-2.0.0/lib/rack/protection/xss_header.rb:18:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-protection-2.0.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-protection-2.0.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-protection-2.0.0/lib/rack/protection/base.rb:50:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-protection-2.0.0/lib/rack/protection/frame_options.rb:31:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-2.0.3/lib/rack/logger.rb:15:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-2.0.3/lib/rack/common_logger.rb:33:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:231:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:224:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/show_exceptions.rb:22:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `block in call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1726:in `synchronize'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/sinatra-2.0.0/lib/sinatra/base.rb:1499:in `call'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/thin-1.7.0/lib/thin/connection.rb:86:in `block in pre_process'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/thin-1.7.0/lib/thin/connection.rb:84:in `catch'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/thin-1.7.0/lib/thin/connection.rb:84:in `pre_process'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/thin-1.7.0/lib/thin/connection.rb:50:in `block in process'
	/usr/local/rvm/gems/ruby-2.3.3@ssh_scan/gems/eventmachine-1.2.3/lib/eventmachine.rb:1076:in `block in spawn_threa

**Comment by claudijd** [comment]
Fixed in https://github.com/mozilla/ssh_scan_api/commit/921fa5ebc210a55c6aa0c0c4df9cbb4ddd4f3eef
