### ISSUE TITLE
Port bug

### ISSUE THREAD

**Issue by claudijd** [mozilla/ssh_scan_api#65]
/root/code/ssh_scan/lib/ssh_scan/result.rb:38:in `port=': Invalid attempt to set port to a non-port value (ArgumentError)
        from /root/code/ssh_scan/lib/ssh_scan/scan_engine.rb:26:in `scan_target'
        from /root/code/ssh_scan/lib/ssh_scan/scan_engine.rb:171:in `block (2 levels) in scan'

**Comment by claudijd** [comment]
Things that might repro this include...

Target: sklep.sportprofit.pl/
Target: https://www.polcard.pl
Target: undefined (or blank)

**Comment by claudijd** [comment]
I fixed the above example cases in a separate merge FWIW, but I suspect the port bug is still present, just need a repro case.
